### PR TITLE
Update dependencies and various cleanups, Resolves #2

### LINKED ISSUE #2: Upgrade to Discord.js v14
Currently this project is running with discord.js v12. The required contribution is to upgrade to the latest version of discord.js v14 while focusing on the functionality of each command. If you want to look into implementing the other slash commands feature, make sure to look into the previous issue #1. Let me know if you need any help!
I will add a link to the contributors page on README once the PR is accepted and merged! Thank you!

### PR DESCRIPTION
**Pull request by camdenorrb**
- Updates all Node dependencies
- Cleans up various things
- Adds better safety in some specific scenarios (Site name not provided in command for example)

### CODE REVIEW

**Review by the94air — CHANGES_REQUESTED** [review]
Would be great if we can have the `package-lock.json` removed!

**Comment by camdenorrb** [comment]
@the94air Curious as to why, but I'll go ahead and remove it

**Comment by the94air** [comment]
It's just a good security practice when there are huge changes on project dependencies. You can read more about this https://snyk.io/blog/why-npm-lockfiles-can-be-a-security-blindspot-for-injecting-malicious-modules/

**Comment by camdenorrb** [comment]
@the94air Ah, very interesting. Thanks for sharing

**Review by the94air — CHANGES_REQUESTED** [review]
The implementation looks pretty straightforward. Great job on that. These are my notes:
- It's great to see that you had to migrate to another monitoring library with better typescript support
- Would be great if we can keep using airbnb-eslint config
- Currently the interval value is set in milliseconds and it needs to be switched to minutes instead. The user will enter the interval in minutes on discord and it should be converted to minutes when it's being applied on the `new Monitor` class
- I would like you to add a `package.json` script similar to `"serve": "tsnd --respawn server.ts"` for running the testing server `src/server.ts`. I find it pretty easier to run a local server and then connect it with the service ngrok for easy down/up testing.
- I am getting some errors whenever I run the `!refresh` `!restart` `!suspend` `!stop` commands due to an error on the `monitor.on('stop', function (monitor, res) {` event
```ts
file:///monitord/dist/controller.js:317
            const gotResponse = res.data;
                                    ^

TypeError: Cannot read properties of undefined (reading 'data')
    at Monitor.<anonymous> (file:///monitord/dist/controller.js:317:37)
    at Monitor.emit (node:events:526:28)
    at Monitor.stop (file:///monitord/node_modules/availability-monitor/dist/src/monitor.js:49:14)
    at Monitor.restart (file:///monitord/node_modules/availability-monitor/dist/src/monitor.js:53:14)
    at Object.restartMonitoring (file:///monitord/dist/controller.js:364:21)
    at file:///monitord/dist/controller.js:231:22
    at Array.forEach (<anonymous>)
    at Object.refresh (file:///monitord/dist/controller.js:227:24)
    at Client.<anonymous> (file:///monitord/dist/index.js:60:24)
```
After these changes are applied, I will do some stability testing and merge afterwards :+1:

**Comment by the94air** [comment]
Thanks for the contribution, I'll take it from here! :+1:

**Pull request merged**
